### ISSUE TITLE
收藏功能本来就不行，但是连续点击之后又出现一个新错误：收藏失败

### ISSUE THREAD

**Issue by hjqcan** [bottos-project/bottos#23]
![image](https://user-images.githubusercontent.com/4464006/38608566-50f5f5ca-3dae-11e8-8262-bd51e1e7aab4.png)
收藏功能本来就不行，但是连续点击之后又出现一个新错误：收藏失败

**Comment by BottosGroup** [comment]
We will fix it this week.
