### ISSUE TITLE
个人发布的需求无法编辑修改，也无法删除

### ISSUE THREAD

**Issue by quantmod** [bottos-project/bottos#31]
个人发布的需求无法编辑修改，也无法删除
![image](https://user-images.githubusercontent.com/8849775/38658996-f79f1e78-3e59-11e8-93d2-84597074fe57.png)

**Comment by BottosGroup** [comment]
In the blockchain system , all these are piblished by contracts. So they aren't to be deleted. But we hope to make them invalid and hide them. This will be supported in the next version.
Thank you.
