### ISSUE TITLE
可以发布代币为0的需求，为了生态良性循环和对贡献者的有偿报酬，是否应该设定期望价格有个最低值，避免充满了各种免费需求，无法刺激数据供给方提供数据

### ISSUE THREAD

**Issue by quantmod** [bottos-project/bottos#34]
可以发布代币为0的需求，为了生态良性循环和对贡献者的有偿报酬，是否应该设定期望价格有个最低值，避免充满了各种免费需求，无法刺激数据供给方提供数据
![image](https://user-images.githubusercontent.com/8849775/38659579-b5bcdb1e-3e5c-11e8-941d-fdc67c39d70e.png)

**Comment by BottosGroup** [comment]
Good idea! Hope it next version.
