### ISSUE TITLE
win10系统 个人发布资产时点击上传样例和上传资产按钮时，弹出获取文件资源库失败 另外上传样例和上传资产初次使用者不知道是啥，很容易混淆，是否可以添加描述性语言或者帮助文档，方便初次使用者理解

### ISSUE THREAD

**Issue by quantmod** [bottos-project/bottos#35]
win10系统
个人发布资产时点击上传样例和上传资产按钮时，弹出获取文件资源库失败
另外上传样例和上传资产初次使用者不知道是啥，很容易混淆，是否可以添加描述性语言或者帮助文档，方便初次使用者理解

![image](https://user-images.githubusercontent.com/8849775/38659693-26a34656-3e5d-11e8-954a-0662ee66f00d.png)
![image](https://user-images.githubusercontent.com/8849775/38659698-2c58a50a-3e5d-11e8-937d-5a74e12d6d25.png)

**Comment by BottosGroup** [comment]
Thanks .  Next version we will improve it.
