### ISSUE TITLE
Error after add keystore

### ISSUE THREAD

**Issue by korjique** [bottos-project/bottos#64]
![9](https://user-images.githubusercontent.com/38522295/38979316-773f9c26-43c2-11e8-88c3-d051f4753ef6.png)
![10](https://user-images.githubusercontent.com/38522295/38979322-79cf5ae4-43c2-11e8-8922-59813bee488f.png)

**Comment by zhanghuicong2008** [comment]
We have solved this problem in version 2.2.0, thank you .
