### ISSUE TITLE
There must be some action on screen once we buy asset. It allows us to buy same asset multiple times and amount gets deducted

### ISSUE THREAD

**Issue by sbhavesha** [bottos-project/bottos#66]
There must be some action on screen once we buy asset. It allows us to buy same asset multiple times and amount gets deducted.
![buyasset_multipletimes](https://user-images.githubusercontent.com/38599162/39091465-f81321a0-4611-11e8-9812-adb227f5e9b2.png)

**Comment by zhanghuicong2008** [comment]
We will solve the problem soon.
