### ISSUE TITLE
Demand details should be in the same sequence within the 'Market Demand' and the 'Demand Details' page. 

### ISSUE THREAD

**Issue by Gissoes** [bottos-project/bottos#90]
[Suggestions.docx](https://github.com/bottos-project/bottos/files/1939831/Suggestions.docx)

**Comment by Gissoes** [comment]
Hi, 
I have sent the wrong attachment, the right attachment is given in this post. 
Sorry for the inconvenience. 
![bottos bug 13](https://user-images.githubusercontent.com/38670520/39173257-8a5a7bb0-47a4-11e8-9e67-4be3cd8bd7bf.png)

**Comment by zhanghuicong2008** [comment]
We have solved this problem in version 2.2.0, thank you .
