### ISSUE TITLE
Harden storage service against SQL injection

### ISSUE THREAD

**Issue by blockauditech** [bottos-project/bottos#93]
We didn't dig too deep to see if these functions are currently exposed to users or otherwise external data, but concatenating SQL queries with function parameters is rarely safe to do.

**service/storage/internal/platform/sqlite/sqlite-tx.go**

```
// Read
func (c *SqliteContext) readOneTx(tx string) (*util.TxDBInfo, error) {
	rows, err := c.db.Query("SELECT * FROM txinfo where TransactionID=" + tx) // HERE
	if err != nil {
		log.Fatal(err)
		return nil, errors.New("readOneTx sql query failed")
	}
```

**service/storage/internal/platform/sqlite/sqlite-user.go**

```
// Read
func (c *SqliteContext) readOne(user string) (*util.UserDBInfo, error) {
	rows, err := c.db.Query("SELECT * FROM userinfo where Username=" + user) // HERE
	if err != nil {
		return nil, errors.New("readOne sql query failed")
	}
	defer rows.Close()
```

These should be replaced with prepared statements to prevent injection and/or the tx and user parameters should be explicitly sanitized and be eg. alphanumeric only to prevent any malformed data from getting through to cause security issues. Otherwise if these functions are truely internal and are never used, fixing these issues can be deprioritized but should not be ever exposed externally until mitigated.

References:
http://go-database-sql.org/prepared.html
https://astaxie.gitbooks.io/build-web-application-with-golang/en/09.4.html

**Comment by luomeiqin** [comment]
@blockauditech, thank you for your detail description of issue and advise. If you dig into these code, you will find that these functions are not exported to users right now. The codes that you are analyzing are in the Bottos's service layer, which delivering database service pluggable to provide users with queries. These databases are imported optionally to serve different DApps in one blockchain node. At present, we release 2.0 version of bottos , which only supports mongodb to provide users with queries, and the functions of the Sqlite database that provided here are not ready yet.

**Comment by blockauditech** [comment]
Sure, that's what we thought but wanted to make sure.

Another thing you can do to help, if not a code change itself, is annotate the code with comments that state this is unsafe concatenation of SQL queries in the functions and they should never be exposed to users. May save one from issues down the road if they somehow get exposed externally for use during code churn or new features.

**Comment by blockauditech** [comment]
Very nice work!

Thanks for making sure users have a secure experience with your product :-)

**Comment by luomeiqin** [comment]
Thank you, We hope that you will continue to favor us with your support.
